title: site
pages: true
fields:
  title:
    label: Title
    type:  text

  description:
   label: Descrizione per facebook e twitter
   type:  textarea
   validate:
     maxLength: 140

  footertext:
   label: Testo di contatto nel footer
   type:  textarea

  tags:
   label: Tags per google
   type:  tags
   width: 1/2
  
  sharedimage:
   label: Immagine per i social
   type:  image
   width: 1/2

  email:
   label: Email
   type:  email

  facebook:
   label: Facebook
   type:  url
   width: 1/2

  instagram:
   label: instagram
   type:  url
   width: 1/2




  