title: site
pages: true
fields:
  title:
    label: Title
    type:  text

  description:
   label: Descrizione per facebook e twitter
   type:  textarea
   validate:
     maxLength: 140

  tags:
   label: Tags per google
   type:  tags
   width: 1/2
  
  sharedimage:
   label: Immagine per i social
   type:  image
   width: 1/2

  indirizzo:
   label: Via, civico, codice di avviamento postale e città
   type:  text
   width: 1/3

  fax:
   label: Fax
   type:  tel
   width: 1/3

  tel:
   label: Telefono
   type:  tel
   width: 1/3

  email:
   label: Email
   type:  email

  facebook:
   label: Facebook
   type:  url
   width: 1/2

  instagram:
   label: instagram
   type:  url
   width: 1/2




  